version: '2'
services:
   micro: 
      image: yogeshnagaruk/microservices-micro
      ports:
         - 8082:8083
   kuber:
      image: yogeshnagaruk/microservices-kuber
      ports:
         - 8081:8082